openapi: 3.0.0
info:
  title: Concentrador de servicios
  description: Aplicacion realizada con Microprofile, Payara y Jakarta EE
  license:
    name: Eclipse Public License - v 1.0
    url: https://www.eclipse.org/legal/epl-v10.html
  version: 1.0.0
servers:
- url: http://localhost:8080